import { Metadata } from "next";
// import { ErrorWrapper } from "./error-wrapper";

export const metadata: Metadata = {
  title: {
    default: "Next.js Tutorial - Codevolution",
    template: "%s | Codevolution",
  },
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className=" bg-gray-500 ">
        {/* <ErrorWrapper> */}
        {children}
        {/* </ErrorWrapper> */}
      </body>
    </html>
  );
}